### ISSUE TITLE
Crash running the current homebrew version

### ISSUE THREAD

**Issue by igorkulman** [yonaskolb/XcodeGen#554]
I installed `xcodegen` from Homebrew. Running `xcodegen` gives me

```
dyld: Symbol not found: _$s11SubSequenceSlTl
  Referenced from: /usr/local/bin/xcodegen
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/xcodegen
Abort trap: 6
```

**Comment by igorkulman** [comment]
I have Xcode 10.2 installed and `xcode-select -p` reports the path is set correctly to the Xcode 10.2 installation.

**Comment by yonaskolb** [comment]
Is your Xcode 10.2 installation `/Applications/Xcode.app`? It looks like it's looking for swift libraries in there

**Comment by igorkulman** [comment]
No, different folder.

**Comment by yonaskolb** [comment]
Does it work if you rename your Xcode installations so 10.2 is that path? Also are you on the latest macOS?

**Comment by piellarda** [comment]
I got the same issue although it's running Xcode 10.1.

**Comment by igorkulman** [comment]
Works fine on another computer with XCode 10.2 in `/Applications/Xcode.app`

**Comment by yonaskolb** [comment]
It might be you need macOS 10.14.4 that bundles Swift 5, or Xcode 10.2 in the default path

**Comment by igorkulman** [comment]
I plan to upgrade from 10.14.3 to 10.14.4 over the weekend, will report back.

**Comment by piellarda** [comment]
Yeah updating from 10.14.3 to 10.14.4 fixed for me, also had the same error with Carthage.

**Comment by igorkulman** [comment]
Works fine on 10.14.4. @yonaskolb it might be worth stating it in the README.
